blog:
   path: /
   controller: App\Controller\BlogController::index

gallery:
   path: /gallery
   controller: App\Controller\GalleryController::index

admin:
   path: /admin
   controller: App\Controller\AdminController::index

post:
   path: /admin/post
   controller: App\Controller\PostController::index

createPost:
   path: /admin/post/create
   controller: App\Controller\PostController::create

editPost:
   path: /admin/post/{postId}/edit
   defaults: { postId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\PostController::edit

deletePost:
   path: /admin/post/{postId}/delete
   defaults: { postId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\PostController::delete

serializePost:
   path: /admin/post/serialize
   controller: App\Controller\PostController::serialize

deserializePost:
   path: /admin/post/deserialize
   controller: App\Controller\PostController::deserialize

category:
   path: /admin/category
   controller: App\Controller\CategoryController::index

createCategory:
   path: /admin/category/create
   controller: App\Controller\CategoryController::create

editCategory:
   path: /admin/category/{categoryId}/edit
   defaults: { categoryId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\CategoryController::edit

categoryPosts:
   path: /admin/category/{categoryId}/posts
   defaults: { categoryId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\CategoryController::getPosts

deleteCategory:
   path: /admin/category/{categoryId}/delete
   defaults: { categoryId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\CategoryController::delete

tag:
   path: /admin/tag
   controller: App\Controller\TagController::index

createTag:
   path: /admin/tag/create
   controller: App\Controller\TagController::create

editTag:
   path: /admin/tag/{tagId}/edit
   defaults: { tagId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\TagController::edit

tagPosts:
   path: /admin/tag/{tagId}/posts
   defaults: { tagId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\TagController::getPosts

deleteTag:
   path: /admin/tag/{tagId}/delete
   defaults: { tagId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\TagController::delete

serializeTag:
   path: /admin/tag/serialize
   controller: App\Controller\TagController::serialize

user:
   path: /admin/user
   controller: App\Controller\UserController::index

editUser:
   path: /admin/user/{userId}/edit
   defaults: { userId: null}
   requirements:
        page: '\d+'
   controller: App\Controller\UserController::edit

deleteUser:
   path: /admin/user/{userId}/delete
   defaults: { userId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\UserController::delete

serializeUser:
   path: /admin/user/serialize
   controller: App\Controller\UserController::serialize

deserialize:
   path: /admin/user/deserialize
   controller: App\Controller\UserController::deserialize

registration:
   path: /admin/user/create
   controller: App\Controller\RegistrationController::register

role:
   path: /admin/role
   controller: App\Controller\RoleController::index

createRole:
   path: /admin/role/create
   controller: App\Controller\RoleController::create

editRole:
   path: /admin/role/{roleId}/edit
   defaults: { roleId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\RoleController::edit

roleUsers:
   path: /admin/role/{roleId}/users
   defaults: { roleId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\RoleController::getUsers
   
deleteRole:
   path: /admin/role/{roleId}/delete
   defaults: { roleId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\RoleController::delete

login:
   path: /login
   controller: App\Controller\SecurityController::login
   methods: GET|POST

logout:
   path: /logout
   methods: GET

json:
   path: /admin/json
   controller: App\Controller\JsonController::index






