blog:
   path: /
   controller: App\Controller\BlogController::index

gallery:
   path: /gallery
   controller: App\Controller\GalleryController::index

admin:
   path: /admin
   controller: App\Controller\AdminController::index

post:
   path: /admin/post
   controller: App\Controller\PostController::index

category:
   path: /admin/category
   controller: App\Controller\CategoryController::index

tag:
   path: /admin/tag
   controller: App\Controller\TagController::index

user:
   path: /admin/user
   controller: App\Controller\UserController::index

editUser:
   path: /admin/user/{userId}/edit
   defaults: { userId: null}
   requirements:
        page: '\d+'
   controller: App\Controller\UserController::edit

deleteUser:
   path: /admin/user/{userId}/delete
   defaults: { userId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\UserController::delete

registration:
   path: /admin/user/create
   controller: App\Controller\RegistrationController::register

role:
   path: /admin/role
   controller: App\Controller\RoleController::index

createRole:
   path: /admin/role/create
   controller: App\Controller\RoleController::create

deleteRole:
   path: /admin/role/{roleId}/delete
   defaults: { roleId: null}
   requirements:
      page: '\d+'
   controller: App\Controller\RoleController::delete

login:
   path: /login
   controller: App\Controller\SecurityController::login
   methods: GET|POST

logout:
   path: /logout
   methods: GET





